version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app1:
    build: ./app
    environment:
      - PORT=8080
      - APP_NAME=app1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo.rule=PathPrefix(`/`)"
      - "traefik.http.services.demo.loadbalancer.server.port=8080"
    expose:
      - "8080"

  app2:
    build: ./app
    environment:
      - PORT=8080
      - APP_NAME=app2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo.rule=PathPrefix(`/`)"
      - "traefik.http.services.demo.loadbalancer.server.port=8080"
    expose:
      - "8080"

